export const transaction = {
  description: 'FAN MOTOR의 GLAND PLATE에 CABLE 인입용 HOLE이 없어 HOLE 이 없어 HOLE 가공을 요청.',
  descriptionHash: 'afc9edc666c3dbc49cd26b4cefcb2b874b163357eb36ff85cff7455fe068cef2',
  code: 'GN-CV02',
  keywords: '가공, 인입용 HOLE, FAN MOTOR',
  id: '16',
  previousTransactionId: '15',
  version: 'CCSRev.1.0',
  previousVersion: 'CCSRev.0.2',
}

export const documents = [
  {
    id: '1',
    eventTime: '2021.10.20. 16:50',
    blockId: '1',
    transactionId: '1',
    sender: 'greedycatty@gmail.com',
    receiver: '-',
    subject: '-',
    transactionHash: '-',
  },
  {
    id: '2',
    eventTime: '2021.10.20. 16:58',
    blockId: '2',
    transactionId: '1',
    sender: 'greedycatty@gmail.com',
    receiver: 'adooublea@gmail.com',
    subject: 'dfbe6d9a02487bfac6c0a80f36fb213f44b95f17ba3de95827593f045bc0e56d',
    transactionHash: '-',
  },
  {
    id: '3',
    eventTime: '',
    blockId: '',
    transactionId: '',
    sender: '',
    receiver: '',
    subject: '',
    transactionHash: '',
  },
  {
    id: '4',
    eventTime: '',
    blockId: '',
    transactionId: '',
    sender: '',
    receiver: '',
    subject: '',
    transactionHash: '',
  },
  {
    id: '5',
    eventTime: '',
    blockId: '',
    transactionId: '',
    sender: '',
    receiver: '',
    subject: '',
    transactionHash: '',
  },
  {
    id: '6',
    eventTime: '',
    blockId: '',
    transactionId: '',
    sender: '',
    receiver: '',
    subject: '',
    transactionHash: '',
  },
  {
    id: '7',
    eventTime: '',
    blockId: '',
    transactionId: '',
    sender: '',
    receiver: '',
    subject: '',
    transactionHash: '',
  },
  {
    id: '8',
    eventTime: '',
    blockId: '',
    transactionId: '',
    sender: '',
    receiver: '',
    subject: '',
    transactionHash: '',
  },
  {
    id: '9',
    eventTime: '',
    blockId: '',
    transactionId: '',
    sender: '',
    receiver: '',
    subject: '',
    transactionHash: '',
  },
  {
    id: '10',
    eventTime: '',
    blockId: '',
    transactionId: '',
    sender: '',
    receiver: '',
    subject: '',
    transactionHash: '',
  },
  {
    id: '11',
    eventTime: '',
    blockId: '',
    transactionId: '',
    sender: '',
    receiver: '',
    subject: '',
    transactionHash: '',
  },
  {
    id: '12',
    eventTime: '',
    blockId: '',
    transactionId: '',
    sender: '',
    receiver: '',
    subject: '',
    transactionHash: '',
  },
  {
    id: '13',
    eventTime: '',
    blockId: '',
    transactionId: '',
    sender: '',
    receiver: '',
    subject: '',
    transactionHash: '',
  },
  {
    id: '14',
    eventTime: '',
    blockId: '',
    transactionId: '',
    sender: '',
    receiver: '',
    subject: '',
    transactionHash: '',
  },
  {
    id: '15',
    eventTime: '',
    blockId: '',
    transactionId: '',
    sender: '',
    receiver: '',
    subject: '',
    transactionHash: '',
  },
  {
    id: '16',
    eventTime: '',
    blockId: '',
    transactionId: '',
    sender: '',
    receiver: '',
    subject: '',
    transactionHash: '',
  },
  {
    id: '17',
    eventTime: '',
    blockId: '',
    transactionId: '',
    sender: '',
    receiver: '',
    subject: '',
    transactionHash: '',
  },
  {
    id: '18',
    eventTime: '',
    blockId: '',
    transactionId: '',
    sender: '',
    receiver: '',
    subject: '',
    transactionHash: '',
  },
]

export const genesisTransaction = {
  description: '-',
  descriptionHash: '-',
  code: '-',
  keywords: '-',
  id: '-',
  previousTransactionId: '-',
  version: '-',
  previousVersion: '-',
}
